### PR TITLE
MongoDB Adapter fix and updates for scenarios

### LINKED ISSUE #1190: Mongo DB driver does not recognize connection parameter
**Describe the bug**
Mongo DB driver does not recognize connection parameter when running `mongodb-crud-basic` workload.

**To Reproduce**
Executed the following command:

```
nb5 -v mongodb-crud-basic docscount=200 threads=20 connection=mongodb://127.0.0.1 database=testdb
```

Output includes the following stack trace:

```
     734 INFO  [main] NBCLI        Configured scenario log at logs/scenario_20230324_155214_572.log
     738 INFO  [main] NBCLI        Running NoSQLBench Version 5.17.2-release
     739 INFO  [main] NBCLI        command-line: -v mongodb-crud-basic docscount=200 threads=20 connection=mongodb://127.0.0.1 database=testdb
    1334 INFO  [main] NBCLI        client-hardware: {"if-speeds":["0Mib","290Mib","9Mib","95Mib"],"physical-cores":"6","max-frequency-ghz":"0.00","logical-cores":"12","sockets":"1","memory-GiB":"32.00","processor-name":"Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz","heap-max-GiB":"8.00"}
    1546 INFO  [main] OpsLoader    workload URI: 'file:///Users/jeffreycarpenter/nosqlbench/adapter-mongodb/src/main/resources/activities/mongodb-crud-basic.yaml'
    1629 INFO  [main] ANNOTATION   {"layer":"CLI","start":1679698335824,"end":1679698335824,"labels":{"layer":"CLI","session":"scenario_20230324_155214_572","span":"instant","appname":"nosqlbench"},"details":{"cli":"-v\nmongodb-crud-basic\ndocscount\u003d200\nthreads\u003d20\nconnection\u003dmongodb://127.0.0.1\ndatabase\u003dtestdb"}}
    1631 INFO  [main] NBCLI        console logging level is INFO
    1642 INFO  [main] NBCLI        Charting disabled
    1643 INFO  [scenarios:001] ANNOTATION   {"layer":"Scenario","start":1679698335841,"end":1679698335841,"labels":{"layer":"Scenario","session":"scenario_20230324_155214_572","span":"instant","appname":"nosqlbench"},"details":{"engine":"Graalvm"}}
    2927 INFO  [scenarios:001] ANNOTATION   {"layer":"Activity","start":1679698337122,"end":1679698337122,"labels":{"layer":"Activity","alias":"mongodbcrudbasic_default_schema","session":"scenario_20230324_155214_572","span":"instant","appname":"nosqlbench"},"details":{"command":"run","params":"ActivityDef:(1)/{database\u003dtestdb, driver\u003dmongodb, threads\u003d1, workload\u003dmongodb-crud-basic, alias\u003dmongodbcrudbasic_default_schema, connection\u003dmongodb://127.0.0.1, tags\u003dblock:\"schema.*\", docscount\u003d200}"}}
    2939 INFO  [scenarios:001] OpsLoader    workload URI: 'file:///Users/jeffreycarpenter/nosqlbench/adapter-mongodb/src/main/resources/activities/mongodb-crud-basic.yaml'
    2960 INFO  [scenarios:001] OpsLoader    workload URI: 'file:///Users/jeffreycarpenter/nosqlbench/adapter-mongodb/src/main/resources/activities/mongodb-crud-basic.yaml'
    3020 INFO  [ACTIVITY:001] ACTIVITY     defaulting stride to 4 (the sequence length)
    3021 INFO  [ACTIVITY:001] ACTIVITY     defaulting cycles to 4 (the stride length)
    3022 INFO  [ACTIVITY:001] ACTIVITY     setting threads to 1 (direct)
    3025 INFO  [ACTIVITY:001] ActivityExecutor starting activity mongodbcrudbasic_default_schema for cycles [0..4)=4
    3025 INFO  [ACTIVITY:001] ANNOTATION   {"layer":"Activity","start":1679698337223,"end":1679698337223,"labels":{"layer":"Activity","alias":"mongodbcrudbasic_default_schema","driver":"mongodb","workload":"mongodb-crud-basic","session":"scenario_20230324_155214_572","span":"instant","appname":"nosqlbench"},"details":{"params":"ActivityDef:(2)/{database\u003dtestdb, driver\u003dmongodb, threads\u003d1, workload\u003dmongodb-crud-basic, alias\u003dmongodbcrudbasic_default_schema, connection\u003dmongodb://127.0.0.1, cycles\u003d4, stride\u003d4, tags\u003dblock:\"schema.*\"}"}}
    3093 INFO  [scenarios:001] ANNOTATION   {"layer":"Activity","start":1679698337291,"end":1679698337291,"labels":{"layer":"Activity","alias":"mongodbcrudbasic_default_write","session":"scenario_20230324_155214_572","span":"instant","appname":"nosqlbench"},"details":{"command":"run","params":"ActivityDef:(1)/{database\u003dtestdb, driver\u003dmongodb, threads\u003d20, workload\u003dmongodb-crud-basic, alias\u003dmongodbcrudbasic_default_write, cycles\u003d200, connection\u003dmongodb://127.0.0.1, errors\u003dtimer,warn, tags\u003dblock:main-write, docscount\u003d200}"}}
    3098 INFO  [scenarios:001] OpsLoader    workload URI: 'file:///Users/jeffreycarpenter/nosqlbench/adapter-mongodb/src/main/resources/activities/mongodb-crud-basic.yaml'
    3106 INFO  [scenarios:001] OpsLoader    workload URI: 'file:///Users/jeffreycarpenter/nosqlbench/adapter-mongodb/src/main/resources/activities/mongodb-crud-basic.yaml'
    3100 ERROR [mongodbcrudbasic_default_schema:001] CoreMotor    Error in core motor loop:java.lang.RuntimeException: while binding request in cycle 0: Parameter named 'connection' is not valid for BaseDriverAdapter.
java.lang.RuntimeException: while binding request in cycle 0: Parameter named 'connection' is not valid for BaseDriverAdapter.
	at io.nosqlbench.engine.api.activityimpl.uniform.actions.StandardAction.runCycle(StandardAction.java:82)
	at io.nosqlbench.engine.api.activityimpl.motor.CoreMotor.run(CoreMotor.java:393)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: io.nosqlbench.api.config.standard.NBConfigError: Parameter named 'connection' is not valid for BaseDriverAdapter.
	at io.nosqlbench.api.config.standard.NBConfiguration.get(NBConfiguration.java:115)
	at io.nosqlbench.adapter.mongodb.core.MongoSpace.<init>(MongoSpace.java:46)
	at io.nosqlbench.adapter.mongodb.core.MongodbDriverAdapter.lambda$getSpaceInitializer$0(MongodbDriverAdapter.java:42)
	at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1708)
	at io.nosqlbench.engine.api.activityimpl.uniform.DriverSpaceCache.get(DriverSpaceCache.java:56)
	at io.nosqlbench.adapter.mongodb.core.MongoOpMapper.lambda$apply$0(MongoOpMapper.java:43)
	at io.nosqlbench.adapter.mongodb.dispensers.MongoCommandOpDispenser.lambda$createOpFunc$5(MongoCommandOpDispenser.java:64)
	at io.nosqlbench.adapter.mongodb.dispensers.MongoCommandOpDispenser.apply(MongoCommandOpDispenser.java:72)
	at io.nosqlbench.adapter.mongodb.dispensers.MongoCommandOpDispenser.apply(MongoCommandOpDispenser.java:32)
	at io.nosqlbench.engine.api.activityimpl.uniform.actions.StandardAction.runCycle(StandardAction.java:80)
	... 4 more
    3108 ERROR [mongodbcrudbasic_default_schema:001] ActivityExceptionHandler Uncaught exception in thread 'mongodbcrudbasic_default_schema:001, state[RUNNABLE], notifying executor 'ActivityExecutor~mongodbcrudbasic_default_schema': java.lang.RuntimeException: while binding request in cycle 0: Parameter named 'connection' is not valid for BaseDriverAdapter.
    3109 INFO  [mongodbcrudbasic_default_schema:001] ActivityExecutor stopping activity mongodbcrudbasic_default_schema:Errored:⌀(0) ⏫(0) ⏵(0) ⏬(0) ⏹(0) ⏯(0) ⚠(1)
```

**Additional context**
OS: macOS
version info 5.17.2-release

### PR DESCRIPTION
**Pull request by jeffbanks**
Includes:

- Fixes #1190 
- Cleanup of other mongodb scenarios
- Debug entries included for more diagnostics
- Includes a dataset file for use with running MongoDB dataset scenario

### CODE REVIEW

File: adapter-mongodb/src/main/java/io/nosqlbench/adapter/mongodb/core/MongoOpMapper.java [hunk 1]
```diff
@@ -39,26 +40,29 @@ public MongoOpMapper(MongodbDriverAdapter adapter) {
...
     @Override
     public OpDispenser<? extends Op> apply(ParsedOp op) {
+
         LongFunction<String> ctxNamer = op.getAsFunctionOr("space", "default");
+        String connectionValue = op.getStaticConfigOr("connection", "unknown");
+
+        if (connectionValue == null) {
+            throw new BasicError("Must provide a connection value for use be MongoDB adapter.");
+        }
+        adapter.setConnection(connectionValue);
```
Comment (jshook) [inline adapter-mongodb/src/main/java/io/nosqlbench/adapter/mongodb/core/MongoOpMapper.java:50]: The connection should be part of the space. Adapters should be considered stateless except for the space, which is the designated state holder for each named instance.

File: adapter-mongodb/src/main/java/io/nosqlbench/adapter/mongodb/core/MongoSpace.java [hunk 2]
```diff
@@ -36,48 +36,52 @@
 public class MongoSpace implements NBNamedElement {
     private final String name;
     private final NBConfiguration cfg;
-    private final String connectionString;
+    private final String connection;
     private final MongoClient client;
     private MongoDatabase mongoDatabase;
 
-    public MongoSpace(String name, NBConfiguration cfg) {
+    public MongoSpace(String name, String connection, NBConfiguration cfg) {
```
Comment (jshook) [inline adapter-mongodb/src/main/java/io/nosqlbench/adapter/mongodb/core/MongoSpace.java:43]: connection should be a lazy-init value within this space

File: adapter-mongodb/src/main/java/io/nosqlbench/adapter/mongodb/core/MongodbDriverAdapter.java [hunk 3]
```diff
@@ -18,33 +18,64 @@
...
 
     @Override
     public NBConfigModel getConfigModel() {
-        return super.getConfigModel().add(MongoSpace.getConfigModel());
+
+        NBConfigModel mongoConfigModel = MongoSpace.getConfigModel();
+        NBConfigModel parentModel = super.getConfigModel();
+        final NBConfigModel merged = mongoConfigModel.add(parentModel);
+
+        if (logger.isDebugEnabled()) {
```
Comment (jshook) [inline adapter-mongodb/src/main/java/io/nosqlbench/adapter/mongodb/core/MongodbDriverAdapter.java:58]: This specialized debug logic having to do with NBConfig* mechanisms should be moved into it or removed altogether. It would be even better as new unit tests and javadoc.

File: adapter-mongodb/src/main/java/io/nosqlbench/adapter/mongodb/dispensers/MongoCommandOpDispenser.java [hunk 4]
```diff
@@ -30,40 +29,33 @@
...
-            .orElseGet(() -> op.getAsOptionalFunction("read-preference")
-                .orElse(l -> "primary"));
-        LongFunction<ReadPreference> readPreferenceF = l -> ReadPreference.valueOf(rpstring.apply(l));
-
         LongFunction<?> payload = op.getAsRequiredFunction("stmt", Object.class);
         Object exampleValue = payload.apply(0);
 
         LongFunction<Bson> bsonFunc;
-        if (exampleValue instanceof CharSequence cs) {
+        if (exampleValue instanceof CharSequence) {
```
Comment (jshook) [inline adapter-mongodb/src/main/java/io/nosqlbench/adapter/mongodb/dispensers/MongoCommandOpDispenser.java:46]: Code formatting on this is retrograde. The modern Java 17 syntax should be preferred everywhere.

File: adapter-mongodb/src/main/resources/activities/mongodb-basic.yaml [hunk 5]
```diff
@@ -2,49 +2,45 @@ description: An example of a basic mongo insert and find.
...
+    rampup: run driver=mongodb tags==block:"rampup.*", cycles===TEMPLATE(rampup-cycles,10) threads=auto errors=timer,warn
+    write: run driver=mongodb tags==block:"write.*", cycles===TEMPLATE(write-cycles,10) threads=auto errors=timer,warn
+    read: run driver=mongodb tags==block:"read.*", cycles===TEMPLATE(read-cycles,10) threads=auto errors=timer,warn
 
 bindings:
-  seq_key: Mod(<<keyCount:1000000>>L); ToInt()
-  seq_value: Mod(<<valueCount:1000000000>>L); <<valueSizeDist:Hash()>>; ToString() -> String
-  rw_key: <<keyDist:Uniform(0,1000000)->long>>; ToInt()
-  rw_value: <<valDist:Uniform(0,1000000000)->int>>; <<valueSizeDist:Hash()>>; ToString() -> String
+  seq_key: Mod(<<keyCount:1000000>>); ToString() -> String
```
Comment (jshook) [inline adapter-mongodb/src/main/resources/activities/mongodb-basic.yaml:10]: All versions of *.ToString return a String, so this output type qualifier is not explicitly required. This could confuse users who think it is.

File: adapter-mongodb/src/main/resources/activities/mongodb-basic.yaml [hunk 6]
```diff
@@ -2,49 +2,45 @@ description: An example of a basic mongo insert and find.
...
-  main-read:
-    params:
-      ratio: <<read_ratio:1>>
-      readPreference: primary
-      type: read
-    ops:
-      main-find: |
+  read:
+    ops:     
+      find: >2
```
Comment (jshook) [inline adapter-mongodb/src/main/resources/activities/mongodb-basic.yaml:28]: Nice use of this YAMLism, maybe we can add this to docs?

File: adapters-api/src/main/java/io/nosqlbench/engine/api/activityimpl/BaseOpDispenser.java [hunk 7]
```diff
@@ -29,59 +29,49 @@
...
-    private final String name;
+    private final String opName;
     protected final DriverAdapter<T, S> adapter;
     private boolean instrument;
     private Histogram resultSizeHistogram;
     private Timer successTimer;
     private Timer errorTimer;
-    private String[] timerStarts = new String[0];
-    private String[] timerStops = new String[0];
+    private final String[] timerStarts;
```
Comment (jshook) [inline adapters-api/src/main/java/io/nosqlbench/engine/api/activityimpl/BaseOpDispenser.java:46]: Nice catch, maybe we can see what the perf diff on this with conditional is vs 0-length iteration.

File: nb-api/src/main/java/io/nosqlbench/api/config/standard/NBConfiguration.java [hunk 8]
```diff
@@ -41,13 +41,22 @@ protected NBConfiguration(NBConfigModel model, LinkedHashMap<String, Object> val
         this.model = model;
     }
 
+    public LinkedHashMap<String, Object> getData() {
```
Comment (jshook) [inline nb-api/src/main/java/io/nosqlbench/api/config/standard/NBConfiguration.java:44]: Let's hide this data and force type-safe access through model-checked accessors.

File: nb-api/src/main/java/io/nosqlbench/api/engine/activityimpl/ParameterMap.java [hunk 9]
```diff
@@ -335,6 +335,7 @@ public interface Listener {
     public Map<String,String> getStringStringMap() {
         return new HashMap<String,String>() {{
             for (Entry entry : ParameterMap.this.entrySet()) {
+                logger.debug("entry: {}, value: {}",entry.getKey(), entry.getValue());
```
Comment (jshook) [inline nb-api/src/main/java/io/nosqlbench/api/engine/activityimpl/ParameterMap.java:338]: If you can, wrap this in a `debug(()->...)` closure

**Review by jshook — CHANGES_REQUESTED** [review]
A few changes should be made before merging this

**Comment by jeffreyscarpenter** [comment]
No specific comments from me, looks good overall. I wanted to test this locally and tried building using `mvn package` but got a failure message after about 6 minutes (confirmed I am building with JDK 17):

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-assembly-plugin:3.3.0:single (assemble-nb) on project nb5: Failed to create assembly: Error creating assembly archive jar-with-dependencies: IOException when zipping rMETA-INF/native/libnetty_tcnative_osx_x86_64.jnilib: File too large -> [Help 1]
[ERROR]
```

File: adapter-mongodb/src/main/resources/activities/mongodb-crud-basic.yaml [hunk 10]
```diff
@@ -7,10 +7,10 @@ description: |
 scenarios:
   default:
     schema:   run driver=mongodb tags==block:"schema.*" threads==1 cycles==UNDEF
-    write:    run driver=mongodb tags==block:main-write,type:write cycles===TEMPLATE(write-cycles,TEMPLATE(docscount,10000000)) threads=auto errors=timer,warn
-    read:     run driver=mongodb tags==block:main-read,type:read cycles===TEMPLATE(read-cycles,TEMPLATE(docscount,10000000)) threads=auto errors=timer,warn
-    update:   run driver=mongodb tags==block:main-update,type:update cycles===TEMPLATE(update-cycles,TEMPLATE(docscount,10000000)) threads=auto errors=timer,warn
-    delete:   run driver=mongodb tags==block:main-delete,type:delete cycles===TEMPLATE(delete-cycles,TEMPLATE(docscount,10000000)) threads=auto errors=timer,warn
+    write:    run driver=mongodb tags==block:"write.*", cycles===TEMPLATE(write-cycles,TEMPLATE(docscount,10)) threads=auto errors=timer,warn
```
Comment (jeffreyscarpenter) [inline adapter-mongodb/src/main/resources/activities/mongodb-crud-basic.yaml:10]: I like this change. Was going to propose something similar but looks like you have it covered.

File: adapter-mongodb/src/main/java/io/nosqlbench/adapter/mongodb/core/MongoOpMapper.java (hunk 1 above)
Comment (jeffbanks) [reply adapter-mongodb/src/main/java/io/nosqlbench/adapter/mongodb/core/MongoOpMapper.java:50]: This makes sense.  I'll adjust those.

File: adapter-mongodb/src/main/java/io/nosqlbench/adapter/mongodb/dispensers/MongoCommandOpDispenser.java (hunk 4 above)
Comment (jeffbanks) [reply adapter-mongodb/src/main/java/io/nosqlbench/adapter/mongodb/dispensers/MongoCommandOpDispenser.java:46]: Correct, that isn't used anywhere for this particular logic.

**Review by jshook — APPROVED** [review]
LGTM
There are some interface improvements needed in the DriverAdapter APIs to help changes like this, but that should be a separate scope.
