### PR TITLE
Handle nested parantheses in TEMPLATE processing

### LINKED ISSUE #1008: `TEMPLATE` function isn't working on certain `<<..>>` replacements
**Describe the bug**
A `TEMPLATE()` should be able to cover all cases where `<<..>>` was used before. The below example binding is erroring out,

```yaml
bindings:
  rw_key: <<keydist:Uniform(0,1000000000)->int>>; ToString() -> String
```
when modified as below,
```yaml
bindings:
  rw_key: TEMPLATE(keydist,Uniform(0,1000000000)->int); ToString() -> String
```
gives the following error when run with `-vv --show-stacktraces`:
<details>
    <summary>Expand/Collapse Stacktrace</summary>

    2788 DEBUG [scenarios:001] StrInterpolator removed template params after applying:{keycount=1000000000, valuecount=1000000000, keydist=Uniform(0,1000000000)->int, valdist=Uniform(0,1000000000)->int, database=baselines, table=keyvalue, read_ratio=5, keyspace=baselines, write_ratio=5}
    line 1:20 extraneous input '->' expecting {',', ')'}
    [->, int]
        2867 WARN  [scenarios:001] VirtDataDSL  Error while parsing flow:Error parsing input 'Uniform(0,1000000000->int); ToString() -> String'
        2878 ERROR [scenarios:001] SCENARIO     Error in scenario, shutting down. (javax.script.ScriptException: java.lang.RuntimeException: Error while parsing binding specification 'Uniform(0,1000000000->int); ToString() -> String': java.lang.RuntimeException: Error parsing input 'Uniform(0,1000000000->int); ToString() -> String')
        2878 DEBUG [scenarios:001] ScenarioController force stopping scenario scenario_20230207_091401_007
        2878 DEBUG [scenarios:001] ScenarioController Scenario force stopped.
        2879 DEBUG [scenarios:001] ScenarioController Requesting ScenarioController shutdown.
        2879 DEBUG [scenarios:001] SCENARIO     finishing scenario
        2879 INFO  [scenarios:001] SCENARIO     Scenario completed successfully, with 0 logical activities.
        2879 INFO  [scenarios:001] SCENARIO     scenario state: Errored
        2880 INFO  [scenarios:001] ANNOTATION   {"layer":"Scenario","start":1675779241971,"end":1675779243550,"labels":{"layer":"Scenario","state":"Errored","session":"scenario_20230207_091401_007","span":"interval","appname":"nosqlbench"},"details":{"command_line":"run\ndriver\u003djdbc\nworkload\u003d/Users/madhavan.sridharan/Data/Tools/sperf_and_nibbler/nosqlbench/local/jdbc/cockroachdb-keyvalue.yaml\ntags\u003dblock:main.*\nthreads\u003dAUTO\ncycles\u003d10\nurl\u003djdbc:postgresql://insectdb0-3153.g8z.cockroachlabs.cloud:26257/defaultdb?sslmode\u003dverify-ca\u0026password\u003dKw67BCIOCxLJrYLWtj2s4g\u0026user\u003dnewuser\ndatabaseName\u003ddefaultdb\nportNumber\u003d26257\nuser\u003dnewuser\npassword\u003dKw67BCIOCxLJrYLWtj2s4g\nsslmode\u003dverify-full\nserverName\u003dinsectdb\nsslrootcert\u003d/Users/madhavan.sridharan/Data/Tools/sperf_and_nibbler/nosqlbench/local/postgresql_certs/root.crt\n-vv\n--show-stacktraces"}}
        2880 DEBUG [scenarios:001] SCENARIO     removing scenario shutdown hook
        2880 DEBUG [scenarios:001] SCENARIO     ERRORED scenario run
        2886 DEBUG [scenarios:001] ExecutionResult populating ERROR scenario result
        2886 DEBUG [scenarios:001] ExecutionResult -- WARNING: Metrics which are taken per-interval (like histograms) will not have --
        2886 DEBUG [scenarios:001] ExecutionResult -- active data on this last report. (The workload has already stopped.) Record   --
        2886 DEBUG [scenarios:001] ExecutionResult -- metrics to an external format to see values for each reporting interval.      --
        2886 DEBUG [scenarios:001] ExecutionResult -- BEGIN METRICS DETAIL --
        2892 DEBUG [scenarios:001] ExecutionResult -- END METRICS DETAIL --
        2896 DEBUG [scenarios:001] SCENARIO     Summarizing counting metrics only to stdout:60 with scenario duration of 60000ms (<60000)
        2903 DEBUG [main] SCENARIOS    scenarios executor shutdown after 1602ms.
        2905 DEBUG [main] NBCLI        Total of 1 result object returned from ScenariosExecutor
        2906 INFO  [main] ScenariosResults results for scenario: name:'scenario_20230207_091401_007'
        2907 INFO  [main] ExecutionResult -- SCENARIO TOOK 1.579S --
        2911 INFO  [main] NBCLI        executions: 1 scenarios, 0 normal, 1 errored
        2912 WARN  [main] NBCLI        executions: 1 scenarios, 0 normal, 1 errored
        2916 ERROR [main] ERRORHANDLER Error from driver or included library: javax.script.ScriptException: java.lang.RuntimeException: Error while parsing binding specification 'Uniform(0,1000000000->int); ToString() -> String': java.lang.RuntimeException: Error parsing input 'Uniform(0,1000000000->int); ToString() -> String'
    java.lang.RuntimeException: javax.script.ScriptException: java.lang.RuntimeException: Error while parsing binding specification 'Uniform(0,1000000000->int); ToString() -> String': java.lang.RuntimeException: Error parsing input 'Uniform(0,1000000000->int); ToString() -> String'
        at io.nosqlbench.engine.core.lifecycle.scenario.Scenario.executeScenarioScripts(Scenario.java:335)
        at io.nosqlbench.engine.core.lifecycle.scenario.Scenario.runScenario(Scenario.java:269)
        at io.nosqlbench.engine.core.lifecycle.scenario.Scenario.call(Scenario.java:406)
        at io.nosqlbench.engine.core.lifecycle.scenario.Scenario.call(Scenario.java:63)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:833)
    Caused by: javax.script.ScriptException: java.lang.RuntimeException: Error while parsing binding specification 'Uniform(0,1000000000->int); ToString() -> String': java.lang.RuntimeException: Error parsing input 'Uniform(0,1000000000->int); ToString() -> String'
        at io.nosqlbench.virtdata.core.bindings.VirtData.getOptionalMapper(VirtData.java:102)
        at io.nosqlbench.virtdata.core.templates.StringCompositor.lambda$new$1(StringCompositor.java:52)
        at java.base/java.util.HashMap.forEach(HashMap.java:1421)
        at io.nosqlbench.virtdata.core.templates.StringCompositor.<init>(StringCompositor.java:51)
        at io.nosqlbench.virtdata.core.templates.StringCompositor.<init>(StringCompositor.java:73)
        at io.nosqlbench.virtdata.core.templates.StringBindings.<init>(StringBindings.java:49)
        at io.nosqlbench.virtdata.core.templates.StringBindings.<init>(StringBindings.java:45)
        at io.nosqlbench.engine.api.templating.ParsedTemplateMap.lambda$applyTemplateFields$1(ParsedTemplateMap.java:124)
        at java.base/java.util.LinkedHashMap.forEach(LinkedHashMap.java:721)
        at io.nosqlbench.engine.api.templating.ParsedTemplateMap.applyTemplateFields(ParsedTemplateMap.java:105)
        at io.nosqlbench.engine.api.templating.ParsedTemplateMap.<init>(ParsedTemplateMap.java:95)
        at io.nosqlbench.engine.api.templating.ParsedOp.<init>(ParsedOp.java:351)
        at io.nosqlbench.engine.api.activityimpl.uniform.StandardActivity.<init>(StandardActivity.java:81)
        at io.nosqlbench.engine.api.activityimpl.uniform.StandardActivityType.getActivity(StandardActivityType.java:59)
        at io.nosqlbench.engine.api.activityimpl.uniform.StandardActivityType.getActivity(StandardActivityType.java:36)
        at io.nosqlbench.engine.api.activityapi.core.ActivityType.getAssembledActivity(ActivityType.java:63)
        at io.nosqlbench.engine.core.lifecycle.activity.ActivityLoader.loadActivity(ActivityLoader.java:44)
        at io.nosqlbench.engine.core.lifecycle.scenario.ScenarioController.doStartActivity(ScenarioController.java:84)
        at io.nosqlbench.engine.core.lifecycle.scenario.ScenarioController.run(ScenarioController.java:137)
        at io.nosqlbench.engine.core.lifecycle.scenario.ScenarioController.run(ScenarioController.java:118)
        at io.nosqlbench.engine.core.lifecycle.scenario.ScenarioController.run(ScenarioController.java:147)
        at io.nosqlbench.engine.core.lifecycle.scenario.script.bindings.PolyglotScenarioController.run(PolyglotScenarioController.java:57)
        at <js>.:program(<eval>:1)
        at org.graalvm.polyglot.Context.eval(Context.java:399)
        at com.oracle.truffle.js.scriptengine.GraalJSScriptEngine.eval(GraalJSScriptEngine.java:478)
        at com.oracle.truffle.js.scriptengine.GraalJSScriptEngine.eval(GraalJSScriptEngine.java:420)
        at java.scripting/javax.script.AbstractScriptEngine.eval(AbstractScriptEngine.java:247)
        at io.nosqlbench.engine.core.lifecycle.scenario.Scenario.executeScenarioScripts(Scenario.java:311)
        ... 7 more
    Caused by: java.lang.RuntimeException: Error while parsing binding specification 'Uniform(0,1000000000->int); ToString() -> String': java.lang.RuntimeException: Error parsing input 'Uniform(0,1000000000->int); ToString() -> String'
        at io.nosqlbench.virtdata.core.bindings.VirtData.getOptionalMapper(VirtData.java:102)
        at io.nosqlbench.virtdata.core.templates.StringCompositor.lambda$new$1(StringCompositor.java:52)
        at java.base/java.util.HashMap.forEach(HashMap.java:1421)
        at io.nosqlbench.virtdata.core.templates.StringCompositor.<init>(StringCompositor.java:51)
        at io.nosqlbench.virtdata.core.templates.StringCompositor.<init>(StringCompositor.java:73)
        at io.nosqlbench.virtdata.core.templates.StringBindings.<init>(StringBindings.java:49)
        at io.nosqlbench.virtdata.core.templates.StringBindings.<init>(StringBindings.java:45)
        at io.nosqlbench.engine.api.templating.ParsedTemplateMap.lambda$applyTemplateFields$1(ParsedTemplateMap.java:124)
        at java.base/java.util.LinkedHashMap.forEach(LinkedHashMap.java:721)
        at io.nosqlbench.engine.api.templating.ParsedTemplateMap.applyTemplateFields(ParsedTemplateMap.java:105)
        at io.nosqlbench.engine.api.templating.ParsedTemplateMap.<init>(ParsedTemplateMap.java:95)
        at io.nosqlbench.engine.api.templating.ParsedOp.<init>(ParsedOp.java:351)
        at io.nosqlbench.engine.api.activityimpl.uniform.StandardActivity.<init>(StandardActivity.java:81)
        at io.nosqlbench.engine.api.activityimpl.uniform.StandardActivityType.getActivity(StandardActivityType.java:59)
        at io.nosqlbench.engine.api.activityimpl.uniform.StandardActivityType.getActivity(StandardActivityType.java:36)
        at io.nosqlbench.engine.api.activityapi.core.ActivityType.getAssembledActivity(ActivityType.java:63)
        at io.nosqlbench.engine.core.lifecycle.activity.ActivityLoader.loadActivity(ActivityLoader.java:44)
        at io.nosqlbench.engine.core.lifecycle.scenario.ScenarioController.doStartActivity(ScenarioController.java:84)
        at io.nosqlbench.engine.core.lifecycle.scenario.ScenarioController.run(ScenarioController.java:137)
        at io.nosqlbench.engine.core.lifecycle.scenario.ScenarioController.run(ScenarioController.java:118)
        at io.nosqlbench.engine.core.lifecycle.scenario.ScenarioController.run(ScenarioController.java:147)
        at io.nosqlbench.engine.core.lifecycle.scenario.script.bindings.PolyglotScenarioController.run(PolyglotScenarioController.java:57)
        at com.oracle.truffle.host.HostMethodDesc$SingleMethod$MHBase.invokeHandle(HostMethodDesc.java:350)
        at com.oracle.truffle.host.GuestToHostCodeCache$1.executeImpl(GuestToHostCodeCache.java:96)
        at com.oracle.truffle.host.GuestToHostRootNode.execute(GuestToHostRootNode.java:80)
        at com.oracle.truffle.api.impl.DefaultCallTarget.callDirectOrIndirect(DefaultCallTarget.java:85)
        at com.oracle.truffle.api.impl.DefaultRuntimeAccessor$DefaultRuntimeSupport.callInlined(DefaultRuntimeAccessor.java:177)
        at com.oracle.truffle.host.GuestToHostRootNode.guestToHostCall(GuestToHostRootNode.java:102)
        at com.oracle.truffle.host.HostMethodDesc$SingleMethod$MHBase.invokeGuestToHost(HostMethodDesc.java:386)
        at com.oracle.truffle.host.HostExecuteNode.doInvoke(HostExecuteNode.java:871)
        at com.oracle.truffle.host.HostExecuteNode.doOverloadedCached(HostExecuteNode.java:288)
        at com.oracle.truffle.host.HostExecuteNodeGen.executeAndSpecialize(HostExecuteNodeGen.java:241)
        at com.oracle.truffle.host.HostExecuteNodeGen.execute(HostExecuteNodeGen.java:97)
        at com.oracle.truffle.host.HostObject.invokeMember(HostObject.java:454)
        at com.oracle.truffle.host.HostObjectGen$InteropLibraryExports$Cached.invokeMemberNode_AndSpecialize(HostObjectGen.java:2696)
        at com.oracle.truffle.host.HostObjectGen$InteropLibraryExports$Cached.invokeMember(HostObjectGen.java:2678)
        at com.oracle.truffle.api.interop.InteropLibraryGen$CachedDispatch.invokeMember(InteropLibraryGen.java:8328)
        at com.oracle.truffle.js.nodes.function.JSFunctionCallNode$ForeignInvokeNode.executeCall(JSFunctionCallNode.java:1534)
        at com.oracle.truffle.js.nodes.function.JSFunctionCallNode.executeAndSpecialize(JSFunctionCallNode.java:306)
        at com.oracle.truffle.js.nodes.function.JSFunctionCallNode.executeCall(JSFunctionCallNode.java:251)
        at com.oracle.truffle.js.nodes.function.JSFunctionCallNode$InvokeNode.execute(JSFunctionCallNode.java:740)
        at com.oracle.truffle.js.nodes.access.JSWriteCurrentFrameSlotNodeGen.execute_generic4(JSWriteCurrentFrameSlotNodeGen.java:124)
        at com.oracle.truffle.js.nodes.access.JSWriteCurrentFrameSlotNodeGen.execute(JSWriteCurrentFrameSlotNodeGen.java:43)
        at com.oracle.truffle.js.nodes.access.JSWriteCurrentFrameSlotNodeGen.executeVoid(JSWriteCurrentFrameSlotNodeGen.java:330)
        at com.oracle.truffle.js.nodes.binary.DualNode.execute(DualNode.java:118)
        at com.oracle.truffle.js.nodes.function.FunctionBodyNode.execute(FunctionBodyNode.java:73)
        at com.oracle.truffle.js.nodes.function.FunctionRootNode.executeInRealm(FunctionRootNode.java:149)
        at com.oracle.truffle.js.runtime.JavaScriptRealmBoundaryRootNode.execute(JavaScriptRealmBoundaryRootNode.java:88)
        at com.oracle.truffle.api.impl.DefaultCallTarget.callDirectOrIndirect(DefaultCallTarget.java:85)
        at com.oracle.truffle.api.impl.DefaultDirectCallNode.call(DefaultDirectCallNode.java:59)
        at com.oracle.truffle.js.lang.JavaScriptLanguage$ParsedProgramRoot.execute(JavaScriptLanguage.java:245)
        at com.oracle.truffle.api.impl.DefaultCallTarget.callDirectOrIndirect(DefaultCallTarget.java:85)
        at com.oracle.truffle.api.impl.DefaultCallTarget.call(DefaultCallTarget.java:102)
        at com.oracle.truffle.polyglot.PolyglotContextImpl.eval(PolyglotContextImpl.java:1470)
        at com.oracle.truffle.polyglot.PolyglotContextDispatch.eval(PolyglotContextDispatch.java:63)
        ... 12 more
        2930 ERROR [main] ERRORHANDLER cause (see stack trace for details):java.lang.RuntimeException: Error while parsing binding specification 'Uniform(0,1000000000->int); ToString() -> String': java.lang.RuntimeException: Error parsing input 'Uniform(0,1000000000->int); ToString() -> String'
    javax.script.ScriptException: java.lang.RuntimeException: Error while parsing binding specification 'Uniform(0,1000000000->int); ToString() -> String': java.lang.RuntimeException: Error parsing input 'Uniform(0,1000000000->int); ToString() -> String'
    Process finished with exit code 2
</details>

**To Reproduce**
See above bug description to repro the problem behavior.

**What was Expected**
The above form should transparently work.

**Additional context**
OS: macOS Monteray
environment: n/a
version info (`./nb --version` or `java -jar nb.jar --version`): `5.17.1-SNAPSHOT`

**Screenshots, if applicable**
n/a

### PR DESCRIPTION
**Pull request by dave2wave**
closes #1008, #453, and #2073

### CODE REVIEW

**Review by msmygit — DISMISSED** [review]
LGTM 👍🏼 Is there an unit test that we need to add here as well?

**Comment by dave2wave** [comment]
The pattern is used in a unit test, but may not be confrimed.

File: nb-engine/nb-engine-core/src/main/java/io/nosqlbench/engine/api/scenarios/NBCLIScenarioPreprocessor.java [hunk 1]
```diff
@@ -437,28 +433,43 @@ public static List<String> getScripts(boolean defaultIncludes, String... include
...
-            Matcher innerMatcher = innerTemplatePattern.matcher(match);
-            if (innerMatcher.find()) {
-                String innerMatch = innerMatcher.group(1);
-                templates = matchTemplates("TEMPLATE(" + innerMatch + ")", templates);
-                String resolvedInner = templates.getOrDefault(innerMatch.split("[,:]")[0], "");
-                match = match.replace("TEMPLATE(" + innerMatch + ")", resolvedInner);
-            }
+    //    private static final Pattern templatePattern = Pattern.compile("TEMPLATE\\((.+?)\\)");
+    //    private static final Pattern innerTemplatePattern = Pattern.compile("TEMPLATE\\((.+?)\\)");
+    private static final Pattern templatePattern2 = Pattern.compile("<<(.+?)>>");
```
Comment (jshook) [inline nb-engine/nb-engine-core/src/main/java/io/nosqlbench/engine/api/scenarios/NBCLIScenarioPreprocessor.java:438]: The `<<name:default>>` pattern should be deprecated with a warning. We introduced the `TEMPLATE(name,default)` format because it didn't throw off syntax checkers, etc.

Comment (dave2wave) [reply nb-engine/nb-engine-core/src/main/java/io/nosqlbench/engine/api/scenarios/NBCLIScenarioPreprocessor.java:438]: Deprecation warning on the use of <<name:default>> is a new requirement.

Comment (dave2wave) [reply nb-engine/nb-engine-core/src/main/java/io/nosqlbench/engine/api/scenarios/NBCLIScenarioPreprocessor.java:438]: This is now checked.

**Review by jshook — CHANGES_REQUESTED** [review]
We need to know if this causes a regression in nested template variables, as this is used in many workloads. There is a commented out unit test which may be related. In any case, adding a test for two-layer nesting is needed, but no further.

**Comment by dave2wave** [comment]
> We need to know if this causes a regression in nested template variables, as this is used in many workloads. There is a commented out unit test which may be related. In any case, adding a test for two-layer nesting is needed, but no further.

The test uses a degenerate form with only a single ')'. This ambiguity should be fixed by reverting to the prior ')' when unwinding.

**Review by jshook — APPROVED** [review]
LGTM!
