### PR TITLE
Nosqlbench vector fixes

### LINKED ISSUE #1477: align annotations to work with current labeling system

### LINKED ISSUE #1478: sanitize all labels which are used according to the openmetrics exposition format spec

### LINKED ISSUE #1483: Surgical patch around OSHI logging early init

### LINKED ISSUE #1484: Verify that grafana annotator client works with SSL and bearer token

### PR DESCRIPTION
**Pull request by jshook**
Metrics system integration improvements. Each commit is mostly themed around a particular kind of change.

fixes #1484 
fixes #1483
fixes #1478
fixes #1477

### CODE REVIEW

**Review by dave2wave — APPROVED** [review]
I didn't see anything obviously wrong

File: nb-api/src/main/java/io/nosqlbench/api/engine/metrics/reporters/PromExpositionFormat.java [hunk 1]
```diff
@@ -221,4 +222,16 @@ private static void writeEscapedHelp(final Writer writer, final String s) throws
...
+        sanitized = sanitized.replaceAll("\\..+$", "");
+        sanitized = sanitized.replaceAll("-","_");
+        sanitized = sanitized.replaceAll("[^a-zA-Z0-9_]+", "");
+
+        if (!word.equals(sanitized)) {
+            logger.warn("The identifier or value '" + word + "' was sanitized to '" + sanitized + "' to be compatible with monitoring systems. You should probably change this to make diagnostics easier.");
+        }
+        return sanitized;
+    }
+
```
Comment (jshook) [inline nb-api/src/main/java/io/nosqlbench/api/engine/metrics/reporters/PromExpositionFormat.java:236]: remove this code if unused

File: engine-cli/src/main/java/io/nosqlbench/engine/cli/NBCLIOptions.java [hunk 2]
```diff
@@ -44,14 +43,13 @@ public class NBCLIOptions {
...
     private static final String NB_STATE_DIR = "--statedir";
-    private static final String NB_STATEDIR_PATHS = "$NBSTATEDIR:$PWD/.nosqlbench:$HOME/.nosqlbench";
     public static final String ARGS_FILE_DEFAULT = "$NBSTATEDIR/argsfile";
     private static final String INCLUDE = "--include";
 
     private static final String userHome = System.getProperty("user.home");
 
 
-    private static final Map<String,String> DEFAULT_LABELS=Map.of("appname","nosqlbench");
+    private static final Map<String, String> DEFAULT_LABELS = Map.of("appname", "nosqlbench");
```
Comment (jshook) [inline engine-cli/src/main/java/io/nosqlbench/engine/cli/NBCLIOptions.java:52]: Is this not being used? Need to verify that default labels are being applied.

File: engine-clients/src/main/java/io/nosqlbench/engine/clients/grafana/GrafanaTokenAuthenticator.java [hunk 3]
```diff
@@ -0,0 +1,37 @@
+/*
```
Comment (jshook) [inline engine-clients/src/main/java/io/nosqlbench/engine/clients/grafana/GrafanaTokenAuthenticator.java:1]: This should be removed until it is properly implemented.

File: nb-api/src/main/java/io/nosqlbench/api/metadata/SystemId.java [hunk 4]
```diff
@@ -125,4 +172,75 @@ public static String getHostSummary() {
         return gson.toJson(details);
 
     }
+
+    private final static String radixSymbols = "01234567890abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ~-"; // 64 symbols, for 2^6!
```
Comment (jshook) [inline nb-api/src/main/java/io/nosqlbench/api/metadata/SystemId.java:176]: Need to ensure that all characters here are in ordinal order so that alphanumeric sorting still works as expected. More tests needed.

File: nb-api/src/test/java/io/nosqlbench/nb/api/SystemIdTest.java [hunk 5]
```diff
@@ -17,28 +17,61 @@
...
+        assertThat(nodeId).matches("\\d+\\.\\d+\\.\\d+\\.\\d+");
+        logger.info("node id: " + nodeId);
     }
 
     @Test
     public void testNodeFingerprint() {
-        String hash = SystemId.getNodeFingerprint();
-        assertThat(hash).matches("[A-Z0-9]+");
+        String nodeFingerprint = SystemId.getNodeFingerprint();
+        assertThat(nodeFingerprint).matches("[A-Z0-9]+");
```
Comment (jshook) [inline nb-api/src/test/java/io/nosqlbench/nb/api/SystemIdTest.java:45]: missing special characters

**Comment by jshook** [comment]
Reviewed this interactively with Mark. There are some minor nits and potential small bugs, but these will be itemized into the next set of commits.
